# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute a reference shape curve for a collection of profiles
#' 
#' @name lad_shape
#' @usage lad_shape(profileMat, bandwidth, gridprecision, timevec)
#' @param profileMat a matrix of profiles
#' @param bandwidth the bandwidth used in RBF kernel
#' @param gridprecision the precision for grid search
#' @param timevec vector of time
#' @return a vector whose length equals the length of time vector containing
#' the reference variability at each time point
#' @export
NULL

lad_shape <- function(profileMat, bandwidth, gridprecision, timevec) {
    .Call('_CoxPF_lad_shape', PACKAGE = 'CoxPF', profileMat, bandwidth, gridprecision, timevec)
}

#' Compute a reference variability curve for a collection of profiles
#' 
#' @name lad_variability
#' @usage lad_variability(cprofileMat, bandwidth, gridprecision, timevec)
#' @param cprofileMat a matrix of profiles with zero medians
#' @param bandwidth the bandwidth used in RBF kernel
#' @param gridprecision the precision for grid search
#' @param timevec vector of time
#' @return a vector whose length equals the length of time vector containing
#' the reference variability at each time point
#' @export
#' 
#' 
NULL

lad_variability <- function(cprofileMat, bandwidth, gridprecision, timevec) {
    .Call('_CoxPF_lad_variability', PACKAGE = 'CoxPF', cprofileMat, bandwidth, gridprecision, timevec)
}

